name: psalm

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
   psalm:
      name: psalm
      runs-on: ubuntu-latest

      strategy:
         matrix:
            php-version: '8.3'

      timeout-minutes: 15
      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Set up PHP ${{ matrix.php-version }}
           uses: shivammathur/setup-php@v2
           with:
              php-version: ${{ matrix.php-version }}


         - name: Run composer install
           run: composer install

         - name: Run psalm
           run: ./vendor/bin/psalm --output-format=github --update-baseline
